# NumPy Practice

This notebook offers a set of excercises for different tasks with NumPy.

It should be noted there may be more than one different way to do below codes.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()

a1=np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(a1)
a1.shape , a1.ndim , a1.dtype , a1.size ,type(a1)

[1 2 3]


((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
print(a2)
a2.shape, a2.size , a2.ndim , a2.dtype ,type(a2)

[[1 2 3]
 [4 5 6]]


((2, 3), 6, 2, dtype('int32'), numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
print(a3)
a3.shape,a3.ndim,a3.dtype,type(a3),a3.size

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


((1, 3, 3), 3, dtype('int32'), numpy.ndarray, 9)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
ar1_df=pd.DataFrame(a1,index=('Row A','Row B','Row C'),columns=['Numbers'])
ar1_df

Numbers
Row A        1
Row B        2
Row C        3

In [23]:
# Create an array of shape (10, 2) with only ones
arr_shp_10_2=np.ones((10,2)).astype(int) # i converted this to int type , otherwise it will return float type value by-default
print(arr_shp_10_2)
print("shape of this array -->",arr_shp_10_2.shape)
print("size of this array -->", arr_shp_10_2.size)
print("data type of this array-->",arr_shp_10_2.dtype)
print("which type of data it belongs to-->",type(arr_shp_10_2))
print("array with dimension -->",arr_shp_10_2.ndim)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
shape of this array --> (10, 2)
size of this array --> 20
data type of this array--> int32
which type of data it belongs to--> <class 'numpy.ndarray'>
array with dimension --> 2


In [26]:
# Create an array of shape (7, 2, 3) of only zeros
zero_array_shp_7_2_3=np.zeros((7,2,3))
print(zero_array_shp_7_2_3)
print("shape of this array -->",zero_array_shp_7_2_3.shape)
print("size of this array -->", zero_array_shp_7_2_3.size)
print("data type of this array-->",zero_array_shp_7_2_3.dtype)
print("which type of data it belongs to-->",type(zero_array_shp_7_2_3))
print("array with dimension -->",zero_array_shp_7_2_3.ndim)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
shape of this array --> (7, 2, 3)
size of this array --> 42
data type of this array--> float64
which type of data it belongs to--> <class 'numpy.ndarray'>
array with dimension --> 3


In [30]:
# Create an array within a range of 0 and 100 with step 3
arr_range_0to100=np.arange(0,100,3)
arr_range_0to100

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [32]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_random_range_0to10=np.random.randint(0,10,size=(7,2))
arr_random_range_0to10

array([[5, 4],
       [8, 5],
       [6, 8],
       [2, 5],
       [1, 2],
       [6, 0],
       [4, 1]])

In [36]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_random_range_0to1=np.random.random((3,5))
arr_random_range_0to1

array([[0.0392526 , 0.29556609, 0.53099203, 0.86457894, 0.7892075 ],
       [0.03482757, 0.05101619, 0.29804548, 0.66236191, 0.42317744],
       [0.49740694, 0.43473283, 0.03864768, 0.59784471, 0.26934428]])

In [41]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_random_seed=np.random.randint(0,10,size=(4,6))
arr_random_seed

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [46]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_random_range_0to10=np.random.randint(1,10,size=(3,7))
print(arr_random_range_0to10)

# Find the unique numbers in the array you just created
np.unique(arr_random_range_0to10)

[[9 7 9 8 2 1 7]
 [7 8 5 3 8 6 3]
 [1 3 5 3 1 5 7]]


array([1, 2, 3, 5, 6, 7, 8, 9])

In [57]:
# Find the 0'th index of the latest array you created
arr_random_range_0to10[0]

array([9, 7, 9, 8, 2, 1, 7])

In [58]:
# Get the first 2 rows of latest array you created
arr_random_range_0to10[0:2]

array([[9, 7, 9, 8, 2, 1, 7],
       [7, 8, 5, 3, 8, 6, 3]])

In [59]:
# Get the first 2 columns of latest array you created
arr_random_range_0to10[:,0:2]

array([[9, 7],
       [7, 8],
       [1, 3]])

In [60]:
# Get the first 2 values of the first 2 rows of the latest array
arr_random_range_0to10[0:2,0:2]

array([[9, 7],
       [7, 8]])

In [72]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
np.random.seed(1)
arr_random_range_0to10=np.random.randint(0,10,size=(3,5))
arr_ones=np.ones((3,5))
print(arr_random_range_0to10)
print("")
print(arr_ones)

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [79]:
# Add the two arrays together
print(a1)
print("")
print(a2)

print("")
print("sum of both array is")
a1+a2

[1 2 3]

[[1 2 3]
 [4 5 6]]

sum of both array is


array([[2, 4, 6],
       [5, 7, 9]])

In [80]:
# Create another array of ones of shape (5, 3)
arr_ones_shp_5_3=np.ones((5,3))
arr_ones_shp_5_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
# Try add the array of ones and the other most recent array together
print(arr_ones)
print("")
print(arr_ones_shp_5_3)
print("")
print("shape of first array is ",arr_ones.shape)
print("shape of 2nd array is",arr_ones_shp_5_3.shape)
print("")
print("if we try to add both the array it will throw an error")
print("lets try and first see the eroor and then try to resolve it")
arr_ones+arr_ones_shp_5_3

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

shape of first array is  (3, 5)
shape of 2nd array is (5, 3)

if we try to add both the array it will throw an error
lets try and first see the eroor and then try to resolve it


ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [88]:
print("as in above error it shows the error of broadcast, it simply means that there is shape miss-match")
print(""""When operating on two arrays, NumPy compares their shapes element-wise.
      It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when

they are equal, or

one of them is 1""")

print("so, here we make them of equal shape using transpose")
print(arr_ones+arr_ones_shp_5_3.T) # here we transpose its 2nd array 
print("or")
print(arr_ones.T+arr_ones_shp_5_3)# here we transpose first array

as in above error it shows the error of broadcast, it simply means that there is shape miss-match
"When operating on two arrays, NumPy compares their shapes element-wise.
      It starts with the trailing dimensions and works its way forward. Two dimensions are compatible when

they are equal, or

one of them is 1
so, here we make them of equal shape using transpose
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
or
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [91]:
# Create another array of ones of shape (3, 5)
arr_ones_new=arr_ones
arr_ones_new

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
# Subtract the new array of ones from the other most recent array
s=arr_ones+arr_ones_shp_5_3.T
arr_ones_new-s

array([[-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1.]])

In [101]:
# Multiply the ones array with the latest array
arr_multiplied=arr_ones_new*s
arr_multiplied

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [102]:
# Take the latest array to the power of 2 using '**'
arr_multiplied**2

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [103]:
# Do the same thing with np.square()
np.square(arr_multiplied)

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [106]:
# Find the mean of the latest array using np.mean()
print(arr_multiplied)
np.mean(arr_multiplied)


[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


2.0

In [109]:
# Find the maximum of the latest array using np.max()
print(arr_random_range_0to10)
np.max(arr_random_range_0to10)

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]]


9

In [110]:
# Find the minimum of the latest array using np.min()
print(arr_random_range_0to10)
np.min(arr_random_range_0to10)

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]]


0

In [111]:
# Find the standard deviation of the latest array
print(arr_random_range_0to10)
np.std(arr_random_range_0to10)

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]]


2.9181424837652385

In [112]:
# Find the variance of the latest array
print(arr_random_range_0to10)
np.var(arr_random_range_0to10)

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]]


8.515555555555556

In [115]:
# Reshape the latest array to (3, 5, 1)
arr_random_range_0to10.reshape((3,5,1))


array([[[5],
        [8],
        [9],
        [5],
        [0]],

       [[0],
        [1],
        [7],
        [6],
        [9]],

       [[2],
        [4],
        [5],
        [2],
        [4]]])

In [116]:
# Transpose the latest array
arr_random_range_0to10.T

array([[5, 0, 2],
       [8, 1, 4],
       [9, 7, 5],
       [5, 6, 2],
       [0, 9, 4]])

What does the transpose do?

In [118]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr_3_3=np.random.randint(0,10,size=(3,3))
arr_3_2=np.random.randint(0,10,size=(3,2))
print(arr_3_3)
print("")
print(arr_3_2)

[[0 1 8]
 [8 3 9]
 [8 7 3]]

[[6 5]
 [1 9]
 [3 4]]


In [119]:
# Perform a dot product on the two newest arrays you created
np.dot(arr_3_3,arr_3_2)



array([[ 25,  41],
       [ 78, 103],
       [ 64, 115]])

In [122]:
np.dot(arr_3_2.T,arr_3_3)

array([[ 32,  30,  66],
       [104,  60, 133]])

In [125]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(1)
a_random_1=np.random.randint(0,10,size=(4,3))
a_random_2=np.random.randint(0,10,size=(4,3))
print(a_random_1)
print("")
print(a_random_2)

[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]

[[5 2 4]
 [2 4 7]
 [7 9 1]
 [7 0 6]]


In [129]:
# Perform a dot product on the two newest arrays you created
np.dot(a_random_1,a_random_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [130]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them bothnp.dot(a_random_1,a_random_2.T)
np.dot(a_random_1,a_random_2.T)

array([[ 77, 105, 116,  89],
       [ 25,  10,  35,  35],
       [ 43,  72,  76,  43],
       [ 65,  54,  85,  87]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [3]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
np.random.seed(2)

arr_3x3=np.random.randint(0,10,size=(3,3)) 
print(arr_3x3)
arr_3_3_new=np.random.randint(0,10,size=(3,3))  
print("")
print(arr_3_3_new)

[[8 8 6]
 [2 8 7]
 [2 1 5]]

[[4 4 5]
 [7 3 6]
 [4 3 7]]


In [166]:
# Compare the two arrays with '>'
arr_3x3>arr_3_3_new

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [170]:
# Compare the two arrays with '>='
arr_3x3>=arr_3_3_new

array([[ True,  True,  True],
       [False,  True,  True],
       [False, False, False]])

In [169]:
# Find which elements of the first array are greater than 7
print(arr_3x3)
arr_3x3>7

[[8 8 6]
 [2 8 7]
 [2 1 5]]


array([[ True,  True, False],
       [False,  True, False],
       [False, False, False]])

In [171]:
# Which parts of each array are equal? (try using '==')
arr_3x3==arr_3_3_new

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [174]:
# Sort one of the arrays you just created in ascending order
print("original array before sorting")
print(arr_3x3)
print("")
print("array after sorting")
np.sort(arr_3x3)

original array before sorting
[[8 8 6]
 [2 8 7]
 [2 1 5]]

array after sorting


array([[6, 8, 8],
       [2, 7, 8],
       [1, 2, 5]])

In [176]:
# Sort the indexes of one of the arrays you just created
print("original array before indexed sorting")
print(arr_3x3)
print("")
print("after index sorting")
np.argsort(arr_3x3)

original array before indexed sorting
[[8 8 6]
 [2 8 7]
 [2 1 5]]

after index sorting


array([[2, 0, 1],
       [0, 2, 1],
       [1, 0, 2]], dtype=int64)

In [5]:
# Find the index with the maximum value in one of the arrays you've created
print(arr_3x3)
np.argmax(arr_3x3)

[[8 8 6]
 [2 8 7]
 [2 1 5]]


0

In [18]:
arr_new=np.random.randint(0,9,size=(3,3))
print(arr_new)
print()
print(np.argsort(arr_new))
print("")
print(np.argmax(arr_new,axis=0))
print("")
print(np.argmin(arr_new))

[[1 5 2]
 [0 0 4]
 [6 3 1]]

[[0 2 1]
 [0 1 2]
 [2 1 0]]

[2 0 1]

3


In [6]:
# Find the index with the minimum value in one of the arrays you've created
print(a3)
np.argmin(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


0

In [13]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(a3)
np.argmax(a3,axis=1)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[2, 2, 2]], dtype=int64)

In [16]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a4=np.random.randint(0,20,size=(4,5))
print(a4)
np.argmin(a4,axis=0)

[[ 9 12  8  6  1]
 [ 6 19 14  5  7]
 [15 19  2  6  3]
 [13 12 17  6 12]]


array([1, 0, 2, 1, 0], dtype=int64)

In [23]:
# Create an array of normally distributed random numbers


print(np.random.randn(3,5))

[[-0.21706802 -0.11069605  0.5439582  -0.29673933  0.69675408]
 [ 0.05404728 -0.84408314  0.74820756  0.30623359  0.80136392]
 [ 0.9884962   1.01137769  0.76252192 -0.06984125  0.26233548]]


In [35]:
# Create an array with 10 evenly spaced numbers between 1 and 100

a6=np.linspace(1,100,10)
print(a6)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]
